repos:
  - repo: local
    hooks:
      - id: rust-check
        name: rustfmt and clippy
        entry: ./scripts/check-rust.sh check
        language: script
        pass_filenames: false
        files: \.rs$

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: ^scripts/
        types_or: [sh, bash, shell]
        args: ['-x']
